image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - apk update && apk add make gcc build-base
  - pip install -r requirements.txt
  - make publish
  artifacts:
    paths:
    - output
  only:
  - master
